// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxftowdrcvlcxxqvmjqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZnRvd2RyY3ZsY3h4cXZtanFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjkyMTYsImV4cCI6MjA1OTcwNTIxNn0.EsREJ-TtwfxZpgUosPpeKTbOZY1mv_lgFBzx3FdBx9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);